export const MARVEL_LIST = {
  title: "O Infinito Marvel",
  info: "Explore heróis, vilões e todas as histórias épicas que moldam esse mundo incrível.",
  name: "Nome",
  description: "Descrição",
  search: "Buscar",
  searchHero: "Digite o nome",
  cleanSearch: "Limpar pesquisa",
  seriesAvailable: "Participações em Séries",
  comics: "Participações em Quadrinhos",
  series: "Participações em Filmes",
  noDescription: "Nenhuma descrição disponível :(",
  isLoading: "Os heróis já estão chegando...",
  error: "Ihh deu ruim :(",
  loadingMore: "Carregando mais",
  loadMore: "Carregar mais",
  noLoading: "Nada mais para carregar",
  characterNotFound: "Nenhum herói encontrado, tente novamente",
}
